AWSTemplateFormatVersion: 2010-09-09
Description: >-
  scheduler-service

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AccountId:
    Type: String
    Description: AWS account ID
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy

Resources:
  SchedulerEventService:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda to be invoked when a EventBridge event happens, hitting an endpoint to kick off subsequent functionality.
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Handler: handlers/scheduled-event.scheduledEventHandler
      CodeUri: './dist'
      MemorySize: 128
      Timeout: 15
      Policies:
        - Statement:
            - Sid: GetApiKeyPolicy
              Effect: Allow
              Action:
                - apigateway:GET
              Resource: 'arn:aws:apigateway:us-east-1::/apikeys'

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [SchedulerEventService]
    Properties:
      LogGroupName: !Sub /aws/lambda/${SchedulerEventService}
      RetentionInDays: 90
